name: ci
on: 
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  # version:
  #   steps:
  #     - name: Git Version
  #       # You may pin to the exact commit or the version.
  #       # uses: codacy/git-version@fa06788276d7492a2af01662649696d249ecf4cb
  #       uses: codacy/git-version@2.4.0
  #       with:
  #         # The name of the release branch
  #         release-branch: # default is master
  #         # The name of the dev branch
  #         dev-branch: # default is dev
  #         # The prefix to use in the version
  #         prefix: # optional
  #         # The paths to be used to calculate changes (comma-separated)
  #         log-paths: # optional, default is ./
            
  test:
    name: Test And Deploy
    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [20.x]
        deno-version: [1.40.x]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Use Deno Version ${{ matrix.deno-version }}
        uses: denolib/setup-deno@master
        with:
          deno-version: ${{ matrix.deno-version }}
      - name: npm install
        run: npm ci
        env:
          CI: true
      - name: prepare
        run: npm run prepare
        env:
          CI: true
      - name: vitest
        run: npm run test
        env:
          CI: true
      - uses: JS-DevTools/npm-publish@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          registry: "https://npm.pkg.github.com"
      - uses: JS-DevTools/npm-publish@v3
        with:
          token: ${{ secrets.NPM_TOKEN }}

      # - uses: lyzhang1999/npm-publish@v1.0.2
      #   with:
      #     # The NPM access token to use when publishing
      #     token: ${{ secrets.NPM_TOKEN }}
      #     tag: latest
      #     access: public
      #     dry-run: false
      #     check-version: true
      #     greater-version-only: true


  # publish:
  #   name: Publish
  #   runs-on: ubuntu-latest
  #   needs: test
  #   environment: ci
  #   steps:
  #     - uses: lyzhang1999/npm-publish@v1.0.2
  #       with:
  #         # The NPM access token to use when publishing
  #         token: ${{ secrets.NPM_TOKEN }}
  #         tag: latest
  #         access: public
  #         dry-run: false
  #         check-version: true
  #         greater-version-only: true
  # publish:
  #   name: Publish
  #   runs-on: ubuntu-latest
  #   needs: version
  #   steps:
  #     - uses: actions/checkout@v1
  #     - name: Set up Node.js
  #       uses: actions/setup-node@v1
  #       with:
  #         node-version: '20.x'
  #     - name: Publish Package
  #       run: npm publish
  #       env:
  #         NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
